### ISSUE TITLE
Give file tags

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/feckless-weasel#20]
User can tag files. 

Possible Notes
-Notes
-Tests
-Solutions
-Assignments

**Comment by hschmack** [comment]
We can store tags in a string, comma-deliminated list. Or we could create a tags table as discussed here: http://stackoverflow.com/questions/334183/what-is-the-most-efficient-way-to-store-tags-in-a-database

**Comment by gundermanc** [comment]
IMHO CSV doesn't make sense when we have access to a DB and can use a table.

If we want to offer the ability to specify additional tags in the future we can use a table like that page suggests.

Alternatively, we can save space by using bit flags. e.g.: each note has a field called flags that is a TINYINT (8 bits) where each bit represents one tag and we have 8 tags. This approach does potentially have reduced search ability though because when searching we must specify EXACTLY the tags we're searching for or NO tags since all flags are stored in one column.

**Comment by hschmack** [comment]
That's a good point about searching. If that's the case I suggest we create a tags table

**Comment by CatalystOfNostalgia** [comment]
I made them strings. Easiest way to do it given the frontend design choice. Also docs can only have 1 tag...mainly because the tags I designed were somewhat mutually exclusive with each other. Closed ticket.
